# conda env create --file environment.yml
name: aproximacion_de_traza
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pip:
      - customtkinter
      - pillow
      - pyinstaller